# Generated by Django 6.0.3 on 2026-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='website',
            name='accent_color',
            field=models.CharField(default='#22d3ee', max_length=10),
        ),
        migrations.AddField(
            model_name='website',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='global_font',
            field=models.CharField(default='Outfit', max_length=60),
        ),
        migrations.AddField(
            model_name='website',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='primary_color',
            field=models.CharField(default='#6366f1', max_length=10),
        ),
    ]
