# Generated by Django 6.0.3 on 2026-03-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_page_og_image_page_seo_description_page_seo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Paste an SVG for the icon')),
                ('description', models.TextField()),
                ('is_pro', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('head_script', models.TextField(blank=True, help_text='HTML to inject in <head>')),
                ('body_script', models.TextField(blank=True, help_text='HTML to inject near </body>')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstalledPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_plugins', to='core_app.website')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.plugin')),
            ],
            options={
                'unique_together': {('website', 'plugin')},
            },
        ),
    ]
