# Generated by Django 6.0.3 on 2026-03-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='theme',
        ),
    ]
