# Generated by Django 6.0.3 on 2026-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
    ]
