# Generated by Django 6.0.3 on 2026-03-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_website_custom_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain mapping (e.g., example.com)', max_length=255, null=True, unique=True),
        ),
    ]
