# Generated by Django 6.0.3 on 2026-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_website_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='page',
            name='robots_meta',
            field=models.CharField(default='index, follow', max_length=100),
        ),
    ]
