# Generated by Django 6.0.3 on 2026-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_page_canonical_url_page_keywords_page_og_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='favicon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
