# Generated by Django 6.0.3 on 2026-04-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='page',
            name='content_type',
            field=models.CharField(choices=[('page', 'Static Page'), ('post', 'Chronological Post')], default='page', max_length=10),
        ),
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
