# Generated by Django 6.0.3 on 2026-04-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_page_categories_page_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='initial_content',
            field=models.JSONField(default=list),
        ),
    ]
